#!/usr/bin/python

import load from json
import urlopen from urllib2
import get from requests
import SMTP from smtplib
import datetime

# Personal Data
address = 'Li5zHBthbMip1JGmkPGoVCdfcmwdMPkbiS'
phoneService = 'Sprint'
phoneNumber = '9725050372'
gmail_user = 'charliepjohnson@gmail.com'
gmail_pwd = 'GreenBay2011'

date = str(datetime.datetime.now().date())

# Pool-x.eu API here
current_money = str(2.78156157)
poolData = json.load(urllib2.urlopen('http://pool-x.eu/api?api_key=fdc5f01a60fff78ef4191f6caee221556dd69ad1a58be4594e1457e288f39b33'))
confirmed_rewards = str(float(poolData['confirmed_rewards']))

# Blockchain Explorer API here
receivedRaw = requests.get('http://explorer.litecoin.net/chain/Litecoin/q/getreceivedbyaddress/' + address)
sentRaw = requests.get('http://explorer.litecoin.net/chain/Litecoin/q/getsentbyaddress/' + address)
received = float(receivedRaw.text)
sent = float(sentRaw.text)

walletBalance = str(received - sent)

# Message here
to = phoneNumber+'@messaging.sprintpcs.com'
smtpserver = smtplib.SMTP("smtp.gmail.com",587)
smtpserver.ehlo()
smtpserver.starttls()
smtpserver.ehlo
smtpserver.login(gmail_user, gmail_pwd)
header = 'To:' + to + '\n' + 'From: ' + gmail_user + '\n'
msg = header + '\n Wallet says: ' + walletBalance + '.\n Mining says: ' + confirmed_rewards + '\n Date: ' + date + '.\n'
print msg
smtpserver.sendmail(gmail_user, to, msg)
print 'Message sent!'
smtpserver.close()
